default['devstack-chef']['host-ip']
default['devstack-chef']['database-password']
default['devstack-chef']['rabbit-password']
default['devstack-chef']['service-token']
default['devstack-chef']['service-password']
default['devstack-chef']['admin-password']
